version: 2
jobs:
  py3:
    docker:
    - image: python:3-stretch
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          apt-get update
          apt-get install -y libsnappy-dev openjdk-8-jre-headless
          pip install tox coverage
    - run:
        name: run tests
        command: tox -e $CIRCLE_JOB
    - run:
        name: submit code coverage report
        command: |
          # convert `.coverage` to `coverage.xml`
          coverage xml -i
          bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB
workflows:
  version: 2
  build:
    jobs:
    - py3
